version: "3.8"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass QU1Q
  nest:
    container_name: nest
    build: './docker/nest-redis'
    volumes:
      - .:/nest-redis/app
    env_file: 
      - ./.env
    ports:
      - "3000:3000"
    command: sh -c "yarn start:dev nest-redis"
    depends_on: 
      - redis
  first:
    container_name: first
    build: './docker/first'
    volumes:
      - .:/first/app
    env_file: 
      - ./.env
    command: sh -c "yarn start:dev first"
    depends_on: 
      - redis
  second:
    container_name: second
    build: './docker/second'
    volumes:
      - .:/second/app
    env_file:
      - ./.env
    command: sh -c "yarn start:dev second"
    depends_on: 
      - redis
  third:
    container_name: third
    build: './docker/third'
    volumes:
      - .:/third/app
    env_file: 
      - ./.env
    command: sh -c "yarn start:dev third"
    depends_on: 
      - redis
